# Generated by Django 3.2.8 on 2021-11-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursecontent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='is_ppt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='ppt_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
