# Generated by Django 3.2.8 on 2021-11-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211116_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='ppt_location',
        ),
    ]
