# Generated by Django 3.2.8 on 2021-10-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['fullname']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='edf', help_text='Will be shown e.g. when commenting', max_length=30, verbose_name='Full name'),
            preserve_default=False,
        ),
    ]
