# Generated by Django 3.2.8 on 2021-11-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211103_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='timestamp',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='ordered_date',
        ),
    ]
