# Generated by Django 3.2.8 on 2021-11-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursecontent_video'),
        ('student', '0002_userprofile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='course.Courses'),
        ),
    ]
